apiVersion: v1
kind: Pod
metadata:
  name: httpecho-pod
  labels:
    app: httpecho
spec:
  containers:
  - name: httpecho
    image: hashicorp/http-echo
    args:
    - -text="this is a test"
    ports:
    - containerPort: 5678
