apiVersion: v1  # Corrigido de 'apps/v1' para 'v1'
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  username: dXNlcg==   # base64 para 'user'
  pass: cGFzc3dvcmQ=     # base64 para 'password'
